import { SideBarLink } from 'src/app/__models/ui-models/nav-link';

export const SIDEBAR_LINKS: SideBarLink[] = [
	{
		name: 'Lệnh điều vận',
		icon: 'issues',
		url: '/logistic/transaction',
		isActive: false,
		isOver: false,
		roles: [],
		children: [
			{
				name: 'Tạo mới',
				icon: 'plus-square',
				url: '/logistic/transaction/new',
				isActive: false,
				isOver: false,
				roles: [],
				children: [],
			},
			{
				name: 'Lịch điều vận',
				icon: 'calendar',
				url: '/logistic/transaction/schedule',
				isActive: false,
				isOver: false,
				roles: [],
				children: [],
			},
			{
				name: 'Danh sách điều vận',
				icon: 'list-outdent',
				url: '/logistic/transaction/list',
				isActive: false,
				isOver: false,
				roles: [],
				children: [],
			},
		],
	},
	{
		name: 'Danh mục lái xe',
		icon: 'user',
		url: '/logistic/driver',
		isActive: false,
		isOver: false,
		roles: [],
		children: [],
	},
	{
		name: 'Khách hàng',
		icon: 'users',
		url: '/logistic/customer',
		isActive: false,
		isOver: false,
		roles: [],
		children: [],
	},
	{
		name: 'Danh mục phương tiện',
		icon: 'car',
		url: '/logistic/vehicle',
		isActive: false,
		isOver: false,
		roles: [],
		children: [],
	},
	{
		name: 'Đơn vị vận tải',
		icon: 'table',
		url: '/logistic/vendor',
		isActive: false,
		isOver: false,
		roles: [],
		children: [],
	},
	{
		name: 'Danh sách địa điểm',
		icon: 'bookmark',
		url: '/logistic/shipping-route',
		isActive: false,
		isOver: false,
		roles: [],
		children: [],
	},
];
