import { SideBarLink } from 'src/app/__models/ui-models/nav-link';

export const SIDEBAR_LINKS: SideBarLink[] = [
	{
		name: 'Nhóm người dùng',
		icon: 'users',
		url: '/admin/groups',
		isActive: false,
		isOver: false,
		roles: ['ADM_GROUP'],
		children: [],
	},
	{
		name: 'Người dùng',
		icon: 'user',
		url: '/admin/users',
		isActive: false,
		isOver: false,
		roles: ['ADM_USER'],
		children: [],
	},
	{
		name: 'Quản lý Quyền',
		icon: 'issues',
		url: '/admin/roles',
		isActive: false,
		isOver: false,
		roles: ['ADM_CODE'],
		children: [],
	},
	// {
	// 	name: 'Multi Levels',
	// 	icon: 'list-outdent',
	// 	url: '/-/admin/groups',
	// 	isActive: false,
	// 	isOver: false,
	// 	children: [
	// 		{
	// 			name: 'Level 1.1',
	// 			icon: '',
	// 			url: '#',
	// 			isActive: false,
	// 			isOver: false,
	// 			children: [],
	// 		},
	// 		{
	// 			name: 'Level 1.2',
	// 			icon: '',
	// 			url: '/-/admin/groups',
	// 			isActive: false,
	// 			isOver: false,
	// 			children: [],
	// 		},
	// 		{
	// 			name: 'Level 1.3',
	// 			icon: '',
	// 			url: 'javascript(void)',
	// 			isActive: false,
	// 			isOver: false,
	// 			children: [],
	// 		},
	// 	],
	// },
	{
		name: 'Danh mục',
		icon: 'list-outdent',
		url: '/admin/codes',
		isActive: false,
		isOver: false,
		roles: ['ADM_CODE'],
		children: [],
	},
];
